api = "0.8"

[buildpack]
id = "heroku/procfile"
version = "0.0.9999"
name = "Heroku Procfile"
homepage = "https://github.com/heroku/procfile-cnb"
description = "Heroku's Procfile buildpack."
keywords = ["procfile", "processes", "heroku"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "*"

[metadata.release]
image = { repository = "docker.io/heroku/procfile-cnb" }

[[metadata.targets]]
os = "linux"
arch = "amd64"

[[metadata.targets]]
os = "linux"
arch = "arm64"
